package fields

const (
	TwitterName       = "Twitter Name"
	TwitterNameClean  = "twitter clean"
	Name              = "Name"
	Email             = "Email"
	OrderNotes        = "Order Notes"
	AdmissionLevel    = "Admission Level"
	Cabin             = "Cabin"
	CabinNumber       = "Cabin Number"
	TicketID          = "Ticket ID"
	OrderDate         = "Order Date"
	Phone             = "Phone"
	StripeTX          = "Stripe Tx"
	TicketGroup       = "Ticket Group"
	Barcode           = "Barcode"
	CheckedIn         = "Checked In"
	TransportTo       = "Transport To"
	TransportFrom     = "Transport From"
	BeddingRental     = "Bedding Rental"
	BeddingPaid       = "Bedding Paid"
	DepartureTime     = "Departure Time"
	ArrivalTime       = "Arrival Time"
	Badge             = "Badge"
	BusToCamp         = "Bus To Camp"
	BusToAUS          = "Bus To AUS"
	Vegetarian        = "Vegetarian"
	GlutenFree        = "Gluten Free"
	LactoseIntolerant = "Lactose Intolerant"
	FoodComments      = "Food Comments"
)
